# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [2]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0,0,1,1]]).T

In [3]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,3)) - 1
# define syn1
syn1 = 2*np.random.random((3,1)) - 1


#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
iter = 0
syn0_history = [syn0]
syn1_history = [syn1]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [12]:
for iter in range(10000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0)) #a1
    l2 = nonlin(np.dot(l1,syn1)) #a2
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
    l2_error = y - l2
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    l2_delta = l2_error * nonlin(l2,True)
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
     # syn1 update weights
    syn1 += np.dot(l1.T,l2_delta)
    if iter % 2000 == 0:
        print(f'iter:{iter}')
        print(f'l1:\n{l1}')
        print(f'l2:\n{l2}\n')
print("Output After Training:")
print(f'l1:\n{l1}')
print(f'l2:\n{l2}\n')


iter:0
l1:
[[0.29433916 0.14760931 0.9197839 ]
 [0.28406291 0.13021552 0.93116585]
 [0.82436735 0.90719646 0.05087026]
 [0.81701109 0.89419213 0.05947153]]
l2:
[[0.00253079]
 [0.00206105]
 [0.99805543]
 [0.99773295]]

iter:2000
l1:
[[0.29342001 0.14701846 0.920105  ]
 [0.28306509 0.12968929 0.93142946]
 [0.82468696 0.9074611  0.05072069]
 [0.8172691  0.8944942  0.05928487]]
l2:
[[0.0024797 ]
 [0.00201957]
 [0.99809545]
 [0.99777948]]

iter:4000
l1:
[[0.29253723 0.14645307 0.92041203]
 [0.28210721 0.12918586 0.9316816 ]
 [0.82499386 0.90771459 0.05057759]
 [0.81751704 0.89478362 0.05910635]]
l2:
[[0.00243153]
 [0.00198045]
 [0.99813318]
 [0.99782333]]

iter:6000
l1:
[[0.29168812 0.14591115 0.92070612]
 [0.28118632 0.12870343 0.93192318]
 [0.82528903 0.9079578  0.05044045]
 [0.81775566 0.89506136 0.05893532]]
l2:
[[0.00238602]
 [0.0019435 ]
 [0.99816881]
 [0.99786476]]

iter:8000
l1:
[[0.29087028 0.14539092 0.92098823]
 [0.28029975 0.12824041 0.932155  ]
 [0.8255733  0.90819149 0.0503088